School.create(name:"Flatiron School", password: "123")
School.create(name:"App Academy", password: "123")
School.create(name:"General Assembly", password: "123")
School.create(name:"Fullstack Academy", password: "123")

Teacher.create(firstName:"Dr.", lastName:"Kim", username: "1", password:"1", school_id: 1)
Student.create(firstName: "Eric", lastName: "Kim", username:"1", password:"1", isAccount: true)

Classroom.create(name:'WEB-031218', teacher_id: 1)
Classroom.create(name:'WEB-040218', teacher_id: 1)
Classroom.create(name:'WEB-042318', teacher_id: 1)
Classroom.create(name:'WEB-050718', teacher_id: 1)
Classroom.create(name:'WEB-052818', teacher_id: 1)

Schedule.create(student_id: 1, classroom_id: 1)
Schedule.create(student_id: 1, classroom_id: 2)
Schedule.create(student_id: 1, classroom_id: 3)
Schedule.create(student_id: 1, classroom_id: 4)
Schedule.create(student_id: 1, classroom_id: 5)

Assignment.create(description: "Mod 1 Code Challenge", classroom_id:1)
Assignment.create(description: "Mod 2 Code Challenge", classroom_id:1)
Assignment.create(description: "Mod 3 Code Challenge", classroom_id:1)
Assignment.create(description: "Mod 4 Code Challenge", classroom_id:1)
Assignment.create(description: "Final Project", classroom_id:1)

Assignment.create(description: "Mod 1 Code Challenge", classroom_id:2)
Assignment.create(description: "Mod 2 Code Challenge", classroom_id:2)
Assignment.create(description: "Mod 3 Code Challenge", classroom_id:2)
Assignment.create(description: "Mod 4 Code Challenge", classroom_id:2)
Assignment.create(description: "Final Project", classroom_id:2)

Assignment.create(description: "Mod 1 Code Challenge", classroom_id:3)
Assignment.create(description: "Mod 2 Code Challenge", classroom_id:3)
Assignment.create(description: "Mod 3 Code Challenge", classroom_id:3)
Assignment.create(description: "Mod 4 Code Challenge", classroom_id:3)
Assignment.create(description: "Final Project", classroom_id:3)

Assignment.create(description: "Mod 1 Code Challenge", classroom_id:4)
Assignment.create(description: "Mod 2 Code Challenge", classroom_id:4)
Assignment.create(description: "Mod 3 Code Challenge", classroom_id:4)
Assignment.create(description: "Mod 4 Code Challenge", classroom_id:4)
Assignment.create(description: "Final Project", classroom_id:4)

Assignment.create(description: "Mod 1 Code Challenge", classroom_id:5)
Assignment.create(description: "Mod 2 Code Challenge", classroom_id:5)
Assignment.create(description: "Mod 3 Code Challenge", classroom_id:5)
Assignment.create(description: "Mod 4 Code Challenge", classroom_id:5)
Assignment.create(description: "Final Project", classroom_id:5)

Grade.create(grade: 100, student_id: 1, assignment_id: 1)
Grade.create(grade: 100, student_id: 1, assignment_id: 2)
Grade.create(grade: 100, student_id: 1, assignment_id: 3)
Grade.create(grade: 100, student_id: 1, assignment_id: 4)
Grade.create(grade: 100, student_id: 1, assignment_id: 5)

Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 6)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 7)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 8)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 9)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 10)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 11)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 12)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 13)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 14)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 15)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 16)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 17)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 18)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 19)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 20)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 21)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 22)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 23)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 24)
Grade.create(grade: Faker::Number.between(0, 100), student_id: 1, assignment_id: 25)
