Teacher.create(name:"Test", username: "Test")
Student.create(firstName:"Student Name")
Classroom.create(name:"Classroom Test", student_id: 1, teacher_id: 1)
Schedule.create(student_id: 1, classroom_id: 1)
Assignment.create(description: "TEST DESCRIPTION", classroom_id:1)
Grade.create(grade:100, student_id: 1, assignment_id: 1)
